### ISSUE TITLE
UNI-RX lua Script Naming

### ISSUE THREAD

**Issue by MRC3742** [offer-shmuely/frsky-accst-uni-rx-scripts#4]
from MikeBland

A question about the filenames. If we keep the version number in the filename, then we will likely end with several files for each script. Should we fix to a specific filename (e.g. UNI-Activate.LUA), and let Github handle the changes, and perhaps have release files, which may then have version numbers in the filenames?

Mike

**Comment by MRC3742** [comment]
from offer-shmuely

regarding the names, that is a good question
one option is relay on the internal name, what presented here come from the internal code:
  local toolName = "TNS|UNI-Stats V6|TNE"


![image](https://user-images.githubusercontent.com/26642502/229267078-77183abb-7a61-42e4-9bf0-6902c1ca9b0b.png)
![image](https://user-images.githubusercontent.com/26642502/229267083-9527cfd7-ec46-4a16-b18b-6277d6c0a5ea.png)

other option is to change on the github the name whenever there is a change to the internal name

the option of keeping a lot of the same file in a source control (git) does not work well

**Comment by offer-shmuely** [comment]
now that the files can accessed using git, instead of searching on the post
I think it is better to remove the version from the name, but still update it inside the script, so it will be presented on the tools menu, as well as in the title bar
i.e.
UNI-Activate.lua
UNI-Setup.lua
UNI-Statistics.lua

what do you say @MikeBland ?

**Comment by MRC3742** [comment]
We are starting out with a new name script with UNI-RX.
I think we should align all the script versions originally to have all the same version number.
That way we could add all scripts to a single release version number.
Smaller changes would be available for download in the main or sub branches and only do a full release when something significant is changed or added.

Rich

**Comment by offer-shmuely** [comment]
pr #5
