### ISSUE TITLE
Scripts do not work properly with D16 v1 LBT protocols

### ISSUE THREAD

**Issue by ulfhedlund** [offer-shmuely/frsky-accst-uni-rx-scripts#7]
I am not sure if it is me doing something wrong but none of the scripts (Activate v2, Setup v4 and Stats v6) seems to work properly if the Rx is bound to any of the LBT protocols. I had to bind the Rx with FCC protocol to get the Rx code and unlock the Rx once I received the codes from Aloft, as well as doing setup and get stats from the Rx.

I have a Radiomaster TX16S with 4-in-1 internal module, running EdgeTX 2.8.3. The multi-module is running V1.3.3.20 of the module firmware.

**Comment by MikeBland** [comment]
I did some testing and it appears there is a problem with the MPM implementation of FrSky V1 EU protocol when sending SPort data to the Rx.

**Comment by ulfhedlund** [comment]
Since the problems aren't related to the scripts perhaps this issue can be closed? Not sure how this works, please let me know if I need to do something.
